import os
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt

class OfficeAutomation:
    @staticmethod
    def create_word_document(filename, content):
        """
        Creates a Word document with the given content.
        Content can be a string (single paragraph) or a list of strings (multiple paragraphs).
        """
        try:
            doc = Document()
            
            # Add Title
            doc.add_heading(filename.replace(".docx", "").replace("_", " ").title(), 0)
            
            if isinstance(content, list):
                for paragraph in content:
                    doc.add_paragraph(paragraph)
            else:
                # Split by double newlines for paragraphs, or single if needed
                paragraphs = content.split('\n')
                for p in paragraphs:
                    if p.strip():
                        doc.add_paragraph(p.strip())
            
            # Ensure filename has extension
            if not filename.endswith(".docx"):
                filename += ".docx"
                
            # Save to user's Documents folder or current directory
            # For this environment, we'll save to a 'generated_docs' folder in the project root
            output_dir = os.path.join(os.getcwd(), "generated_docs")
            os.makedirs(output_dir, exist_ok=True)
            file_path = os.path.abspath(os.path.join(output_dir, filename))
            
            doc.save(file_path)
            return file_path # Return just the path for the UI to format

        except Exception as e:
            return f"Failed to create Word document: {e}"

    @staticmethod
    def create_presentation(topic, content_slides):
        """
        Creates a PowerPoint presentation.
        content_slides is a list of dictionaries: [{'title': 'Slide 1', 'content': 'Bullet 1\nBullet 2'}]
        """
        try:
            prs = Presentation()
            
            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title = slide.shapes.title
            subtitle = slide.placeholders[1]
            
            title.text = topic
            subtitle.text = "Generated by J.A.R.V.I.S."
            
            # Content Slides
            bullet_slide_layout = prs.slide_layouts[1]
            
            for slide_data in content_slides:
                slide = prs.slides.add_slide(bullet_slide_layout)
                shapes = slide.shapes
                
                title_shape = shapes.title
                body_shape = shapes.placeholders[1]
                
                title_shape.text = slide_data.get('title', 'Slide')
                tf = body_shape.text_frame
                
                content_text = slide_data.get('content', '')
                # Handle bullet points (split by newline)
                lines = content_text.split('\n')
                
                tf.text = lines[0] if lines else ""
                
                for line in lines[1:]:
                    p = tf.add_paragraph()
                    p.text = line
                    p.level = 0 # Top level bullet
            
            filename = f"{topic.replace(' ', '_')}.pptx"
            output_dir = os.path.join(os.getcwd(), "generated_docs")
            os.makedirs(output_dir, exist_ok=True)
            file_path = os.path.join(output_dir, filename)
            
            prs.save(file_path)
            return os.path.abspath(file_path)
        except Exception as e:
            return f"Failed to create Presentation: {e}"
