import os
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt

class OfficeAutomation:
    @staticmethod
    def create_word_document(topic: str, content: str) -> str:
        """
        Creates a Word document using `topic` as the document title.
        Content can be a plain string or newline-separated paragraphs.
        Returns: absolute file path string, or error message string.
        """
        if not topic or not isinstance(topic, str):
            return "Failed to create Word document: 'topic' must be a non-empty string."
        if content is None:
            content = ""

        try:
            doc = Document()

            # Title from topic
            doc.add_heading(topic.strip(), level=0)

            if isinstance(content, list):
                for paragraph in content:
                    if paragraph.strip():
                        doc.add_paragraph(paragraph.strip())
            else:
                for p in content.split('\n'):
                    if p.strip():
                        doc.add_paragraph(p.strip())

            filename = topic.replace(' ', '_').replace('/', '_') + ".docx"
            output_dir = os.path.join(os.getcwd(), "outputs", "documents")
            os.makedirs(output_dir, exist_ok=True)
            file_path = os.path.abspath(os.path.join(output_dir, filename))

            doc.save(file_path)

            if not os.path.exists(file_path):
                return f"Failed to create Word document: file not found after save."

            return file_path

        except Exception as e:
            return f"Failed to create Word document: {e}"

    @staticmethod
    def create_presentation(slides: list) -> str:
        """
        Creates a PowerPoint presentation.
        slides: list of dicts — [{'title': str, 'content': str}]
        The first slide's title is used as the presentation name.
        Returns: absolute file path string, or error message string.
        """
        if not slides or not isinstance(slides, list):
            return "Failed to create Presentation: 'slides' must be a non-empty list."

        try:
            prs = Presentation()

            # Derive presentation title from first slide
            presentation_title = slides[0].get('title', 'Presentation')

            # Title slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            slide.shapes.title.text = presentation_title
            slide.placeholders[1].text = "Generated by J.A.R.V.I.S."

            # Content slides
            bullet_slide_layout = prs.slide_layouts[1]

            for slide_data in slides:
                if not isinstance(slide_data, dict):
                    continue
                s = prs.slides.add_slide(bullet_slide_layout)
                s.shapes.title.text = slide_data.get('title', 'Slide')
                tf = s.placeholders[1].text_frame

                content_text = slide_data.get('content', '')
                lines = content_text.split('\n')
                tf.text = lines[0] if lines else ""
                for line in lines[1:]:
                    p = tf.add_paragraph()
                    p.text = line
                    p.level = 0

            filename = presentation_title.replace(' ', '_').replace('/', '_') + ".pptx"
            output_dir = os.path.join(os.getcwd(), "outputs", "documents")
            os.makedirs(output_dir, exist_ok=True)
            file_path = os.path.abspath(os.path.join(output_dir, filename))

            prs.save(file_path)

            if not os.path.exists(file_path):
                return "Failed to create Presentation: file not found after save."

            return file_path

        except Exception as e:
            return f"Failed to create Presentation: {e}"
